/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 308119d46ddb5abc68a8a568e48bd3da)
interface __BaseEnv_Env {
	RECOVERY: R2Bucket;
	ALLOWED_ORIGIN: "https://j-appleton.github.io";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGIN">> {}
}
